nginx_config_main_template_enable: true
nginx_config_http_template_enable: true

nginx_config_main_template:
  template_file: nginx.conf.j2
  deployment_location: /etc/nginx/nginx.conf
  backup: true
  config:
    main:
      user:
        username: nginx
      worker_processes: auto
      error_log:
        - file: /var/log/nginx/error.log
          level: error
      pid: /var/run/nginx.pid
    events:
      worker_connections: 1024
    http:
      include:
        - /etc/nginx/mime.types
        - /etc/nginx/conf.d/*.conf
    stream:
      include:
        - /etc/nginx/conf.d/streams/*.conf

nginx_config_http_template_for_ssl_configuration:
  - template_file: http/default.conf.j2
    deployment_location: /etc/nginx/conf.d/{{ inventory_hostname }}.conf
    backup: true
    config:
      servers:
        - core:
            listen:
              - port: 80
            server_name: "{{ inventory_hostname }}"
            log:
              access:
                - path: /var/log/nginx/{{ inventory_hostname }}.log
          locations:
            - location: /
              core:
                root: /var/www/{{ inventory_hostname }}
                index: index.html

nginx_config_http_template_main_conf:
  - template_file: http/default.conf.j2
    deployment_location: /etc/nginx/conf.d/default.conf
    backup: true
    config:
      servers:
        - core:
            listen:
              - port: 80
          rewrite:
            return:
              code: 301
              url: https://$host$request_uri
  - template_file: http/default.conf.j2
    deployment_location: /etc/nginx/conf.d/{{ inventory_hostname }}.conf
    backup: true
    config:
      servers:
        - core:
            listen:
              - port: 443
                ssl: true
            server_name: "{{ inventory_hostname }}"
            error_page:
              - code:
                  - 500
                  - 502
                  - 503
                  - 504
                uri: /50x.html
          log:
            access:
              - path: /var/log/nginx/{{ inventory_hostname }}.log
          ssl:
            certificate: /etc/letsencrypt/live/{{ inventory_hostname }}/fullchain.pem
            certificate_key: /etc/letsencrypt/live/{{ inventory_hostname }}/privkey.pem
          locations:
            - location: /50x.html
              core:
                root: /usr/share/nginx/html
            - location: /
              core:
                root: /var/www/{{ inventory_hostname }}
                index: index.html
