- hosts: "{{ env }}"
  gather_facts: yes
  become: true
  collections:
    - nginxinc.nginx_core
  tasks:
  - name: Install nginx
    include_role:
      name: nginxinc.nginx_core
  - name: Install letsencrypt
    include_role:
      name: systemli.letsencrypt
    vars:
      letsencrypt_cert:
        name: "{{ inventory_hostname }}"
        domains:
          - "{{ inventory_hostname }}"
        challenge: http
        services:
          - nginx
  - name: Config nginx
    include_role:
      name: nginxinc.nginx_config
    vars:
      nginx_config_http_template:
        - template_file: http/default.conf.j2
          deployment_location: /etc/nginx/conf.d/default.conf
          backup: true
          config:
            servers:
              - core:
                  listen:
                    - port: 80
                rewrite:
                  return:
                    code: 301
                    url: https://$host$request_uri
#        - template_file: http/default.conf.j2
#          deployment_location: /etc/nginx/conf.d/{{ inventory_hostname }}-app.conf
#          backup: true
#          config:
#            servers:
#              - core:
#                  listen:
#                    - port: 8443
#                      ssl: true
#                  server_name: "{{ inventory_hostname }}"
#                log:
#                  access:
#                    - path: /var/log/nginx/{{ inventory_hostname }}.log
#                ssl:
#                  certificate: /etc/letsencrypt/live/{{ inventory_hostname }}/fullchain.pem
#                  certificate_key: /etc/letsencrypt/live/{{ inventory_hostname }}/privkey.pem
#                locations:
#                  - location: /api
#                    proxy:
#                      pass: http://127.0.0.1:{{ api_listen_docker_port }}
#                      set_header:
#                        - field: Host
#                          value: $host
#                        - field: X-Real-IP
#                          value: $remote_addr
#        - template_file: http/default.conf.j2
#          deployment_location: /etc/nginx/conf.d/{{ inventory_hostname }}.conf
#          backup: true
#          config:
#            servers:
#              - core:
#                  listen:
#                    - port: 443
#                      ssl: true
#                  server_name: "{{ inventory_hostname }}"
#                  error_page:
#                    - code:
#                        - 500
#                        - 502
#                        - 503
#                        - 504
#                      uri: /50x.html
#                log:
#                  access:
#                    - path: /var/log/nginx/{{ inventory_hostname }}.log
#                ssl:
#                  certificate: /etc/letsencrypt/live/{{ inventory_hostname }}/fullchain.pem
#                  certificate_key: /etc/letsencrypt/live/{{ inventory_hostname }}/privkey.pem
#                locations:
#                  - location: /50x.html
#                    core:
#                      root: /usr/share/nginx/html
#                  - location: /
#                    core:
#                      root: /var/www/{{ inventory_hostname }}
#                      index: index.html