name: Nginx config

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "test"
      - "main"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  prepare-hosts:
    environment: ${{ github.event_name == 'push' && github.ref == 'refs/heads/test' && 'test' || github.ref == 'refs/heads/main' && 'prod' }}
    runs-on: ubuntu-20.04
    permissions: write-all
    concurrency: ${{ github.base_ref }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Prepare nginx hosts
        run: |
          ansible-galaxy install -r iaac/ansible/roles/requirements.yml
          eval "$(ssh-agent -s)"
          echo -n ${{ secrets.DEPLOY_SSH_KEY }} | base64 -d | ssh-add -
          ansible-playbook --user ${{ secrets.DEPLOY_SSH_USER }} -i iaac/ansible/inventory \
          iaac/ansible/playbooks/nginx.yml \
          --limit ${{ github.environment }} \
          --extra-vars "\
          ansible_sudo_pass=\"${{ secrets.DEPLOY_USER_PASSWORD }}\"
          ansible_port=\"${{ secrets.DEPLOY_SSH_PORT }}\""
